import type { Campaign, SocialConnection } from "./types";

export const MOCK_CAMPAIGNS: Campaign[] = [
  {
    id: "c1",
    name: "SixZero Coral Code Drop",
    keywords: ["coral", "sixzero coral", "code"],
    platforms: ["instagram", "facebook", "youtube"],
    target_mode: "specific",
    target_post_ids: ["18029384756102938"],
    reply_text: "Just sent you a DM with the code! 🏓",
    dm_text:
      "Hey {{name}}! Here's your SixZero Coral discount code: PLAYBOOK10. Tap below to grab the paddle.",
    cta_link: "https://pickleballplaybook.com/sixzero-coral",
    is_active: true,
    starts_at: null,
    ends_at: null,
    match_once_per_user: true,
    created_at: "2026-05-01T14:23:00Z",
    triggers_count: 142,
    last_triggered_at: "2026-05-07T09:14:00Z",
  },
  {
    id: "c2",
    name: "Free Drill Plan",
    keywords: ["drills", "drill", "free"],
    platforms: ["instagram"],
    target_mode: "all",
    target_post_ids: [],
    reply_text: "Sending you the free 12-week drill plan now! 💪",
    dm_text:
      "Hey {{name}}! Here's the free 12-week drill plan I promised. Download the app for the full experience:",
    cta_link: "https://apps.apple.com/app/pickleball-playbook",
    is_active: true,
    starts_at: null,
    ends_at: null,
    match_once_per_user: true,
    created_at: "2026-04-15T10:00:00Z",
    triggers_count: 67,
    last_triggered_at: "2026-05-06T18:42:00Z",
  },
  {
    id: "c3",
    name: "Academy Waitlist (Q3 Launch)",
    keywords: ["academy", "waitlist", "join"],
    platforms: ["instagram", "facebook"],
    target_mode: "all",
    target_post_ids: [],
    reply_text: "Check your DMs — got the waitlist link for you!",
    dm_text:
      "Welcome {{name}}! Pickleball Playbook Academy is launching soon. Tap below to join the waitlist:",
    cta_link: "https://pickleballplaybookacademy.com/waitlist",
    is_active: false,
    starts_at: "2026-06-01T00:00:00Z",
    ends_at: null,
    match_once_per_user: true,
    created_at: "2026-04-20T16:30:00Z",
    triggers_count: 0,
    last_triggered_at: null,
  },
];

export const MOCK_CONNECTIONS: SocialConnection[] = [
  {
    id: "s1",
    platform: "instagram",
    account_name: "@pickleballplaybook",
    is_active: true,
    connected_at: "2026-04-01T12:00:00Z",
  },
  {
    id: "s2",
    platform: "facebook",
    account_name: "Pickleball Playbook",
    is_active: true,
    connected_at: "2026-04-01T12:05:00Z",
  },
  {
    id: "s3",
    platform: "youtube",
    account_name: "Pickleball Playbook",
    is_active: false,
    connected_at: "2026-04-01T12:10:00Z",
  },
];
